// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changednameinProjectedResaleValueChartmodelclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changednameinProjectedResaleValueChartmodelclass));
        
        string IMigrationMetadata.Id
        {
            get { return "201910031853372_changed name in ProjectedResaleValueChart model class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
